### PR TITLE
Numpy and Scipy deprecation warnings fixed

### PR DESCRIPTION
**Pull request by fjosw**
This PR fixes two deprecation warnings.

### CODE REVIEW

**Comment by fjosw** [comment]
The Numpy deprecation was also addressed in #59 but I think using `tiny` instead of `smallest_normal` should be backward compatible.

**Comment by fjosw** [comment]
Looks like all tests but `PYTHON_VERSION=3.6, MINICONDA=C:\Miniconda36-x64, PYTHON_ARCH=64` succeeded. That one exits with

```
error: Setup script exited with 
Beginning with Matplotlib 3.6, Python 3.8 or above is required.
You are using Python 3.6.5.
This may be due to an out of date pip.
Make sure you have pip >= 9.0.1.
```

which seems to be unrelated to my changes. I guess this is related to #62 and python 3.6 end of life?

**Comment by pbrod** [comment]
Thanks @fjosw  for the effort of making this pullrequest.

**Comment by fjosw** [comment]
My pleasure! Could you maybe release a new version on pypi such that dependencies profit from the changes?

**Comment by pbrod** [comment]
Done!

**Pull request merged**
